// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	activities "genVoice/business/activities"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateActivity provides a mock function with given fields: domain
func (_m *Repository) CreateActivity(domain *activities.Domain) (activities.Domain, error) {
	ret := _m.Called(domain)

	var r0 activities.Domain
	if rf, ok := ret.Get(0).(func(*activities.Domain) activities.Domain); ok {
		r0 = rf(domain)
	} else {
		r0 = ret.Get(0).(activities.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*activities.Domain) error); ok {
		r1 = rf(domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
