// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	invoices "genVoice/business/invoices"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetNotif provides a mock function with given fields: status, signature_key
func (_m *Service) GetNotif(status string, signature_key string) error {
	ret := _m.Called(status, signature_key)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(status, signature_key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserBySignature provides a mock function with given fields: signature_key
func (_m *Service) GetUserBySignature(signature_key string) (invoices.InvoiceDetailDomain, int, error) {
	ret := _m.Called(signature_key)

	var r0 invoices.InvoiceDetailDomain
	if rf, ok := ret.Get(0).(func(string) invoices.InvoiceDetailDomain); ok {
		r0 = rf(signature_key)
	} else {
		r0 = ret.Get(0).(invoices.InvoiceDetailDomain)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(string) int); ok {
		r1 = rf(signature_key)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(signature_key)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
