name : deploy backend
on : 
  pull_request:
    branches :
      - 'main'
  push:
    branches :
      - 'main'
  
jobs:
  unit-test : 
    name : 'unitTest'
    runs-on : ubuntu-latest
    steps:
      - uses : actions/checkout@v2
      - name : setup-go
        uses : actions/setup-go@v2
        with :
          go-version : 1.17
      - name : run-unittest
        run : go test ./... -cover